In [1]:
import pandas as pd 
import os
import glob

In [2]:

#Récupère la liste des fichiers spécifiés par le chemin au format liste

csv_files = glob.glob('C:/Users/HP/Documents/afp/Fichier1/*.csv')

#Afficher la liste des fichiers à lire

for a in csv_files:
    print(a)

#Préparez une liste pour ajouter le contenu du fichier csv

data_list = []

#Scannez la liste des fichiers à lire

for file in csv_files:
    data_list.append(pd.read_csv(file,encoding='latin-1',sep=';'))

#Combinez toutes les listes dans le sens des lignes
#axis=0:Rejoindre dans le sens de la ligne

df = pd.concat(data_list, axis=0)

# Trouver les colonnes qui sont vides 

cols_vides = [col for col in df.columns if df[col].isnull().all()]

# supprimer les colonnes vides  du tableau 

#df.drop(cols_vides, axis=1, inplace=True)

C:/Users/HP/Documents/afp/Fichier1\01-10.csv
C:/Users/HP/Documents/afp/Fichier1\11-15.csv
C:/Users/HP/Documents/afp/Fichier1\16-17.csv
C:/Users/HP/Documents/afp/Fichier1\16-20.csv
C:/Users/HP/Documents/afp/Fichier1\21-25.csv
C:/Users/HP/Documents/afp/Fichier1\26-27.csv
C:/Users/HP/Documents/afp/Fichier1\28-29.csv
C:/Users/HP/Documents/afp/Fichier1\30.csv

In [3]:
df

,numéro,date,heure,type,utilisateur,classe,poids,unité,Poids Max.,surcharge,...,poids max essieu 8,surcharge essieu 8,vitesse essieu 8,accélération essieu 8,violation essieu 8,poids essieu 9,poids max essieu 9,vitesse essieu 9,accélération essieu 9,violation essieu 9
0,1,01/11/21,00:04:43,Pesage en mouvement,ABOUET,Classe T11S2,27480,kg,45600,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,01/11/21,00:08:01,Pesage en mouvement,ABOUET,Classe P12,22480,kg,31200,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,01/11/21,00:10:27,Pesage en mouvement,ABOUET,Classe T11S3,51060,kg,51600,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,01/11/21,00:14:55,Pesage en mouvement,ABOUET,Classe T12S4,60020,kg,74400,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,01/11/21,00:17:48,Pesage en mouvement,ABOUET,Classe T11S3T,41400,kg,55200,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,9163,30/11/21,23:47:23,Pesage en mouvement,oiebrottie,Classe T11S3,25640,kg,51600,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,9164,30/11/21,23:50:20,Pesage en mouvement,oiebrottie,Classe T11S3,24120,kg,51600,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,9165,30/11/21,23:51:52,Pesage en mouvement,oiebrottie,Classe T11S3,35960,kg,51600,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,9166,30/11/21,23:55:08,Pesage en mouvement,oiebrottie,Classe T11S3,59780,kg,51600,8180,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,9167,30/11/21,23:56:48,Pesage en mouvement,oiebrottie,Classe P12,31540,kg,31200,340,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#del df['unité']
#df

,numéro,date,heure,type,utilisateur,classe,poids,Poids Max.,surcharge,vitesse,...,poids max essieu 8,surcharge essieu 8,vitesse essieu 8,accélération essieu 8,violation essieu 8,poids essieu 9,poids max essieu 9,vitesse essieu 9,accélération essieu 9,violation essieu 9
0,1,01/11/21,00:04:43,Pesage en mouvement,ABOUET,Classe T11S2,27480,45600,0,3.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,01/11/21,00:08:01,Pesage en mouvement,ABOUET,Classe P12,22480,31200,0,3.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,01/11/21,00:10:27,Pesage en mouvement,ABOUET,Classe T11S3,51060,51600,0,3.85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,01/11/21,00:14:55,Pesage en mouvement,ABOUET,Classe T12S4,60020,74400,0,2.83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,01/11/21,00:17:48,Pesage en mouvement,ABOUET,Classe T11S3T,41400,55200,0,2.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,9163,30/11/21,23:47:23,Pesage en mouvement,oiebrottie,Classe T11S3,25640,51600,0,5.54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,9164,30/11/21,23:50:20,Pesage en mouvement,oiebrottie,Classe T11S3,24120,51600,0,4.19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,9165,30/11/21,23:51:52,Pesage en mouvement,oiebrottie,Classe T11S3,35960,51600,0,4.31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,9166,30/11/21,23:55:08,Pesage en mouvement,oiebrottie,Classe T11S3,59780,51600,8180,5.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,9167,30/11/21,23:56:48,Pesage en mouvement,oiebrottie,Classe P12,31540,31200,340,5.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#Nombres de doublons

In [6]:
df.duplicated().sum()

588

In [7]:
#Supprimer les doublons

In [8]:
df_sans_doublons=df.drop_duplicates()

In [9]:
df_sans_doublons

,numéro,date,heure,type,utilisateur,classe,poids,Poids Max.,surcharge,vitesse,...,poids max essieu 8,surcharge essieu 8,vitesse essieu 8,accélération essieu 8,violation essieu 8,poids essieu 9,poids max essieu 9,vitesse essieu 9,accélération essieu 9,violation essieu 9
0,1,01/11/21,00:04:43,Pesage en mouvement,ABOUET,Classe T11S2,27480,45600,0,3.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,01/11/21,00:08:01,Pesage en mouvement,ABOUET,Classe P12,22480,31200,0,3.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,01/11/21,00:10:27,Pesage en mouvement,ABOUET,Classe T11S3,51060,51600,0,3.85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,01/11/21,00:14:55,Pesage en mouvement,ABOUET,Classe T12S4,60020,74400,0,2.83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,01/11/21,00:17:48,Pesage en mouvement,ABOUET,Classe T11S3T,41400,55200,0,2.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,9163,30/11/21,23:47:23,Pesage en mouvement,oiebrottie,Classe T11S3,25640,51600,0,5.54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,9164,30/11/21,23:50:20,Pesage en mouvement,oiebrottie,Classe T11S3,24120,51600,0,4.19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,9165,30/11/21,23:51:52,Pesage en mouvement,oiebrottie,Classe T11S3,35960,51600,0,4.31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,9166,30/11/21,23:55:08,Pesage en mouvement,oiebrottie,Classe T11S3,59780,51600,8180,5.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,9167,30/11/21,23:56:48,Pesage en mouvement,oiebrottie,Classe P12,31540,31200,340,5.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#convertir au format xlsx

In [14]:
import openpyxl

with pd.ExcelWriter('base_dedoublonnee.xlsx') as writer:
    df_sans_doublons.to_excel(writer)

In [15]:
#Convertir au format csv

df_sans_doublons.to_csv("fusion.csv",index=False)